### ISSUE TITLE
iPhone 5 會報錯喔..

### ISSUE THREAD

**Issue by ilyi1116** [CoderJackyHuang/HYBSnapkitAutoCellHeight#1]
哈囉，樓主

我用 iphone 5 實體機 ＆ Simulator 都會報錯在 UITableViewCell+AutoCellHeight.swift  第44行

**Comment by CoderJackyHuang** [comment]
如果有报错，请将报错的信息帖出来。同时，请说明xcode的版本！

**Comment by ilyi1116** [comment]
XCODE Version 7.3 (7D175)
報錯的信息是 
Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
**\* -[CFNumber retain]: message sent to deallocated instance 0x7ebf9f50

**Comment by ilyi1116** [comment]
看起來是死在這一段：
  /// 可不指定，若不指定则使用默认值0
 `public var hyb_bottomOffsetToCell: CGFloat? {
    get {
      let offset = objc_getAssociatedObject(self, &__hyb_bottomOffsetToCell);
      return offset as? CGFloat
    }
    set {
      objc_setAssociatedObject(self,
        &__hyb_bottomOffsetToCell,
        newValue,
        .OBJC_ASSOCIATION_ASSIGN);
    }
  }`

死在 lef offset 這一行
